


### Rental Service Requests



### Security Requests



###
GET /api/v1/rental-service/security/csrf-token
Host: localhost:8765
Accept: application/json



### Identity Requests



###
GET /api/v1/rental-service/identities
Host: localhost:8765
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv

###
GET /api/v1/rental-service/identities/by-id?identityId=df7d4c8d-d46b-41e0-a979-e0b8a9d0d873
Host: localhost:8765
Accept: application/json
Authorization: Basic zagor@gmail.com zagor

###
POST /api/v1/rental-service/identities/create
Host: localhost:8765
Accept: application/json
Content-Type: application/json
X-Csrf-Token: efa7af4e-f45c-4996-b4cc-352bb462f4e9

{
    "authority": "USER",
    "username": "danakt",
    "password": "danakt",
    "email": "danakt@gmail.com",
    "enabled": true,
    "firstname": "Осипкин",
    "lastname": "Алексей",
    "patronymic": "Олегович"
}

###
PUT /api/v1/rental-service/identities/update
Host: localhost:8765
Accept: application/json
Content-Type: application/json
X-Csrf-Token: 453471e9-c9bc-4d14-bae8-64a57057c92b
Authorization: Basic zagor@gmail.com zagor

{
    "id": "f7de976b-4b7b-4df4-b57c-15f169b47c68",
    "username": "zagor"
}

###
PUT /api/v1/rental-service/identities/change-status
Host: localhost:8765
Accept: application/json
Content-Type: application/json
X-Csrf-Token: 453471e9-c9bc-4d14-bae8-64a57057c92b
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "id": "f7de976b-4b7b-4df4-b57c-15f169b47c68",
    "enabled": true
}

###
PUT /api/v1/rental-service/identities/change-password
Host: localhost:8765
Accept: application/json
Content-Type: application/json
X-Csrf-Token: 925da406-e751-45d3-bd12-d52ec7d25c49
Authorization: Basic burgasvv@gmail.com burgasvv111

{
    "id": "b666b330-7e92-46b5-8239-4116c3d3802f",
    "password": "burgasvv"
}

###
DELETE /api/v1/rental-service/identities/delete?identityId=f7de976b-4b7b-4df4-b57c-15f169b47c68
Host: localhost:8765
Accept: application/json
X-Csrf-Token: 925da406-e751-45d3-bd12-d52ec7d25c49
Authorization: Basic zagor@gmail.com zagor



### Category Requests



###
GET /api/v1/rental-service/categories
Host: localhost:8765
Accept: application/json

###
GET /api/v1/rental-service/categories/by-id?categoryId=4ca2efb1-947f-4f21-851b-6b56e7b00a3f
Host: localhost:8765
Accept: application/json

###
POST /api/v1/rental-service/categories/create
Host: localhost:8765
Accept: application/json
Content-Type: application/json
X-Csrf-Token: e72413b7-9e35-4d65-9c1e-91ed4ab678fc
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "name": "Офисы",
    "description": "Описание категории Офисы"
}

###
PUT /api/v1/rental-service/categories/update
Host: localhost:8765
Accept: application/json
Content-Type: application/json
X-Csrf-Token: e72413b7-9e35-4d65-9c1e-91ed4ab678fc
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "id": "067b8f92-625f-4f0a-9209-27bf614270ff",
    "name": "Офисы Тест"
}

###
DELETE /api/v1/rental-service/categories/delete?categoryId=067b8f92-625f-4f0a-9209-27bf614270ff
Host: localhost:8765
Accept: application/json
X-Csrf-Token: e72413b7-9e35-4d65-9c1e-91ed4ab678fc
Authorization: Basic burgasvv@gmail.com burgasvv



### Property Requests



###
GET /api/v1/rental-service/properties
Host: localhost:8765
Accept: application/json

###
GET /api/v1/rental-service/properties/by-id?propertyId=2d90e432-0a11-48f2-8832-b6682ba1a66a
Host: localhost:8765
Accept: application/json

###
POST /api/v1/rental-service/properties/create
Host: localhost:8765
Accept: application/json
Content-Type: application/json
X-Csrf-Token: bccf8e66-f7b3-440e-9ee5-83f9ddeac78b
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "categoryId": "4ca2efb1-947f-4f21-851b-6b56e7b00a3f",
    "name": "Аркадьевский Отель",
    "address": "г.Москва, ул.Твардовского, д.44б",
    "description": "Описание недвижимости Аркадьевский Отель",
    "ownerId": "b666b330-7e92-46b5-8239-4116c3d3802f"
}

###
PUT /api/v1/rental-service/properties/update
Host: localhost:8765
Accept: application/json
Content-Type: application/json
X-Csrf-Token: 07510fec-ab72-4841-b6ed-ab7d66bb0b8c
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "id": "ae03cba8-5d06-4b5a-8098-6fe6e42a25e0",
    "address": "г.Москва, ул.Твардовского, д.56/1"
}

###
DELETE /api/v1/rental-service/properties/delete?propertyId=ae03cba8-5d06-4b5a-8098-6fe6e42a25e0
Host: localhost:8765
Accept: application/json
X-Csrf-Token: 07510fec-ab72-4841-b6ed-ab7d66bb0b8c
Authorization: Basic burgasvv@gmail.com burgasvv

###
DELETE /api/v1/rental-service/properties/remove-images?propertyId=2d90e432-0a11-48f2-8832-b6682ba1a66a
Host: localhost:8765
Accept: application/json
Content-Type: application/json
X-Csrf-Token: 9b66e171-5d5d-44a8-8800-938f2785fbee
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "imageIds": [
        "26f0bb4e-fbda-4f2b-9cab-1ada40447470",
        "c8baabb7-f833-4321-8d42-3755723d1653"
    ]
}

###
DELETE /api/v1/rental-service/properties/remove-documents?propertyId=2d90e432-0a11-48f2-8832-b6682ba1a66a
Host: localhost:8765
Accept: application/json
Content-Type: application/json
X-Csrf-Token: 321e7c2b-5820-401b-bb90-2b60e42c963c
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "documentIds": [
        "3a893d72-b84a-4d72-b9ae-f9eb7d6b3323",
        "269853a4-fea5-4b8f-8ca0-23a998e27954"
    ]
}



### Advertisement Requests



###
GET /api/v1/rental-service/advertisements
Host: localhost:8765
Accept: application/json

###
GET /api/v1/rental-service/advertisements/by-id?advertisementId=669ef2e9-bbe8-4c7c-9c72-b0c35ea675a1
Host: localhost:8765
Accept: application/json

###
POST /api/v1/rental-service/advertisements/create
Host: localhost:8765
Accept: application/json
Content-Type: application/json
X-Csrf-Token: bccf8e66-f7b3-440e-9ee5-83f9ddeac78b
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "title": "Аренда Аркадьевского Отеля",
    "description": "Описание аренды Аркадьевского Отеля",
    "propertyId": "f6d413c1-011f-43dd-af80-1236f6107648",
    "price": 150400.50,
    "date": "2026-02-10"
}

###
PUT /api/v1/rental-service/advertisements/update
Host: localhost:8765
Accept: application/json
Content-Type: application/json
X-Csrf-Token: bccf8e66-f7b3-440e-9ee5-83f9ddeac78b
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "id": "1213621c-aff5-4e28-bd0a-e4557f628fed",
    "price": 160500.20
}

###
DELETE /api/v1/rental-service/advertisements/delete?advertisementId=1213621c-aff5-4e28-bd0a-e4557f628fed
Host: localhost:8765
Accept: application/json
X-Csrf-Token: bccf8e66-f7b3-440e-9ee5-83f9ddeac78b
Authorization: Basic burgasvv@gmail.com burgasvv

###
PUT /api/v1/rental-service/advertisements/rent-property
Host: localhost:8765
Accept: application/json
Content-Type: application/json
X-Csrf-Token: bccf8e66-f7b3-440e-9ee5-83f9ddeac78b
Authorization: Basic zagor@gmail.com zagor

{
    "tenantId": "df7d4c8d-d46b-41e0-a979-e0b8a9d0d873",
    "advertisementId": "b434aba1-7458-4cfe-ae46-94de08bdec9a"
}



### Construction Service Requests



### Security Requests



###
GET /api/v1/construction-service/security/csrf-token
Host: localhost:8765
Accept: application/json



### Identity Requests



###
GET /api/v1/construction-service/identities
Host: localhost:8765
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv

###
GET /api/v1/construction-service/identities/by-id?identityId=5c7334fd-8215-4abb-ba91-76609eac15b9
Host: localhost:8765
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv

###
POST /api/v1/construction-service/identities/create
Host: localhost:8765
Accept: application/json
Content-Type: application/json
X-Csrf-Token: 4b1316dd-381d-4852-b342-31d1717dd014

{
    "authority": "USER",
    "username": "zagorulko",
    "password": "zagor",
    "email": "zagor@gmail.com",
    "enabled": true,
    "firstname": "Загорулько",
    "lastname": "Борис",
    "patronymic": "Юрьевич"
}

###
PUT /api/v1/construction-service/identities/update
Host: localhost:8765
Accept: application/json
Content-Type: application/json
X-Csrf-Token: 3f6d60ca-f614-4ae9-ae63-351db89ff03c
Authorization: Basic zagor@gmail.com zagor

{
    "id": "663041ee-0151-486d-b747-7f064d6a9e87",
    "username": "zagor"
}

###
PUT /api/v1/construction-service/identities/change-status
Host: localhost:8765
Accept: application/json
Content-Type: application/json
X-Csrf-Token: 3f6d60ca-f614-4ae9-ae63-351db89ff03c
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "id": "663041ee-0151-486d-b747-7f064d6a9e87",
    "enabled": true
}

###
PUT /api/v1/construction-service/identities/change-password
Host: localhost:8765
Accept: application/json
Content-Type: application/json
X-Csrf-Token: 3f6d60ca-f614-4ae9-ae63-351db89ff03c
Authorization: Basic zagor@gmail.com zagor111

{
    "id": "663041ee-0151-486d-b747-7f064d6a9e87",
    "password": "zagor"
}

###
DELETE /api/v1/construction-service/identities/delete?identityId=663041ee-0151-486d-b747-7f064d6a9e87
Host: localhost:8765
Accept: application/json
X-Csrf-Token: 3f6d60ca-f614-4ae9-ae63-351db89ff03c
Authorization: Basic zagor@gmail.com zagor



### Building Requests



###
GET /api/v1/construction-service/buildings
Host: localhost:8765
Accept: application/json

###
GET /api/v1/construction-service/buildings/by-id?buildingId=77dbcb22-ad63-407f-b452-224d3d70634a
Host: localhost:8765
Accept: application/json

###
POST /api/v1/construction-service/buildings/create
Host: localhost:8765
Accept: application/json
Content-Type: application/json
X-Csrf-Token: ee502178-bab6-4dde-90d6-6d5c32ff5566
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "address": "г.Москва, ул.Долинская, д.15",
    "materials": "Материалы используемые для строительства здания",
    "floors": 15,
    "onObject": 50,
    "description": "Описание данного здания",
    "identityId": "5c7334fd-8215-4abb-ba91-76609eac15b9",
    "built": false
}

###
PUT /api/v1/construction-service/buildings/update
Host: localhost:8765
Accept: application/json
Content-Type: application/json
X-Csrf-Token: ee502178-bab6-4dde-90d6-6d5c32ff5566
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "id": "77dbcb22-ad63-407f-b452-224d3d70634a",
    "floors": 20
}

###
DELETE /api/v1/construction-service/buildings/remove-images?buildingId=77dbcb22-ad63-407f-b452-224d3d70634a
Host: localhost:8765
Accept: application/json
Content-Type: application/json
X-Csrf-Token: 50e445ef-37d9-46ac-bfd0-cc5a15f5b116
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "imageIds": [
        "890843b5-9bdc-47d4-ae83-91ee52b0337b",
        "e7703767-1c01-45f8-8d0b-410a308cbd18"
    ]
}

###
DELETE /api/v1/construction-service/buildings/remove-documents?buildingId=77dbcb22-ad63-407f-b452-224d3d70634a
Host: localhost:8765
Accept: application/json
Content-Type: application/json
X-Csrf-Token: 50e445ef-37d9-46ac-bfd0-cc5a15f5b116
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "documentIds": [
        "afbdd5f2-f2d1-4d72-8746-a2747548b47f"
    ]
}

###
DELETE /api/v1/construction-service/buildings/delete?buildingId=77dbcb22-ad63-407f-b452-224d3d70634a
Host: localhost:8765
Accept: application/json
X-Csrf-Token: 50e445ef-37d9-46ac-bfd0-cc5a15f5b116
Authorization: Basic burgasvv@gmail.com burgasvv